//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblCustomers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCustomers()
        {
            this.TblSales = new HashSet<TblSales>();
        }
    
        public int CustomerID { get; set; }

        [Required(ErrorMessage = "You cannot leave this field blank")]
        [StringLength(50,ErrorMessage= "Enter up to 50 characters")]
        public string CustomerName { get; set; }

        [Required(ErrorMessage = "You cannot leave this field blank")]
        [StringLength(50, ErrorMessage = "Enter up to 50 characters")]
        public string CustomerSurName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSales> TblSales { get; set; }
    }
}
